# Generated by Django 3.0.8 on 2020-07-18 17:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstfloor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friend_list',
            field=models.ManyToManyField(related_name='_profile_friend_list_+', to='firstfloor.Profile'),
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.BooleanField(default=None)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='firstfloor.Profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='firstfloor.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('end_date', models.DateTimeField(default=datetime.datetime.now)),
                ('cancelled', models.BooleanField(default=False)),
                ('private', models.BooleanField(default=False)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_hosted_events', to='firstfloor.Profile')),
                ('invitees', models.ManyToManyField(related_name='profile_event_invitations', to='firstfloor.Profile')),
                ('participants', models.ManyToManyField(related_name='profile_attended_events', to='firstfloor.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now)),
                ('passphrase', models.CharField(blank=True, max_length=50)),
                ('invitation_required', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_created_groups', to='firstfloor.Profile')),
                ('invitees', models.ManyToManyField(blank=True, null=True, related_name='profile_group_invitations', to='firstfloor.Profile')),
                ('participants', models.ManyToManyField(related_name='profile_associated_groups', to='firstfloor.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Unspecified Discussion Topic', max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_created_discussions', to='firstfloor.Profile')),
                ('related_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_discussions', to='firstfloor.DiscussionGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now)),
                ('edit_date', models.DateTimeField(default=datetime.datetime.now)),
                ('contents', models.CharField(max_length=255)),
                ('approval', models.IntegerField(default=0)),
                ('commenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_comments', to='firstfloor.Profile')),
                ('related_discussion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion_comments', to='firstfloor.Discussion')),
            ],
        ),
    ]
