# Generated by Django 3.0.8 on 2020-07-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstfloor', '0002_auto_20200718_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussiongroup',
            name='invitees',
            field=models.ManyToManyField(related_name='profile_group_invitations', to='firstfloor.Profile'),
        ),
    ]
